# Generated by Django 5.2 on 2025-04-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationmessages_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessages',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
